version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server

  server:
    build: ./src
    restart: always
  
  bot:
    build: ./bot
    restart: always
    environment:
      - FLAG=CyKor{example_flag}